surface.CreateFont("roboto_20",{font="Roboto Black",extended=false,size=20,weight=500})
surface.CreateFont("roboto_15",{font="Roboto Black",extended=false,size=15,weight=500})

net.Receive("nyeblock_hintPopup",function()
	local function displayHint()
		local rand = math.random( 20, 120 )
		timer.Simple( rand, function()
			local panel = vgui.Create("DPanel")
			panel:SetSize(300,110)
			panel:SetPos( ScrW() + 530, ScrH() / 2 )
			panel:MoveTo( ScrW() - 285, ScrH() / 2, 1, 0, 1 )
			function panel:Paint(w,h)
				draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
				draw.RoundedBox(0,0,0,15,h,Color(149,165,166))
			end
			local pic = vgui.Create("DImage",panel)
			pic:SetSize(45,45)
			pic:SetPos(15,-2)
			pic:SetImage("materials/nb/logo_45x45.png")
			local label = vgui.Create("DLabel",panel)
			label:SetText("Hint")
			label:SetFont("roboto_20")
			label:SetPos(60,10)
			label:SetColor(Color(52,73,94))
			label:SizeToContents()
			local hint = vgui.Create("DLabel",panel)
			hint:SetSize(panel:GetWide()-50,panel:GetTall()-55)
			hint:SetPos(25,40)
			hint:SetText(table.Random(NYEBLOCK.HINT_POPUPS))
			hint:SetColor(Color(52,73,94))
			hint:SetWrap(true)
			hint:SetFont("roboto_15")
			hint:SetAutoStretchVertical(true)
			timer.Simple(.1,function()
				panel:SizeToChildren(false,true)
				panel:SetHeight(panel:GetTall()+10)
			end)
			timer.Simple( 8, function()
				panel:MoveTo( ScrW() + 500, ScrH() / 2, 1, 0, 1 )
				timer.Simple( 2, function()
					panel:SetVisible( false )
					displayHint()
				end)
			end)
		end)
	end
	displayHint()
end)