surface.CreateFont("oswald_20",{font="Oswald",extended=false,size=20,weight=500})
surface.CreateFont("oswald_24",{font="Oswald",extended=false,size=24,weight=500})
surface.CreateFont("oswald_28",{font="Oswald",extended=false,size=28,weight=500})
surface.CreateFont("oswald_30",{font="Oswald",extended=false,size=30,weight=5000})
surface.CreateFont("roboto_30",{font="Roboto Black",extended=false,size=30,weight=500})
surface.CreateFont("roboto_25",{font="Roboto Black",extended=false,size=25,weight=500})
surface.CreateFont("roboto_20",{font="Roboto Black",extended=false,size=20,weight=500})
surface.CreateFont("roboto_15",{font="Roboto Black",extended=false,size=15,weight=500})
surface.CreateFont("regular_20",{font="",extended=false,size=20,weight=500})
surface.CreateFont("regular_15",{font="",extended=false,size=15,weight=500})

local panel
local pagepanel
local menuselected = 1
local headerButtons = {}
local headerButtonArrows = {}
local buttonSubmenus = {}
local function closeDropdowns()
	for k,v in pairs(buttonSubmenus) do
		v:SetVisible(false)
		headerButtonArrows[k]:SetText("⯅")
	end
end
local function center(i,y)
	if IsValid(pagepanel) then
		i:SetPos(pagepanel:GetWide()/2-i:GetWide()/2,y)
	end
end

local function survey()

end

local function motd()
	pagepanel:AlphaTo(255,.5,0)

	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Message of the 'day'")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,15)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Welcome to NyeBlock's Deathrun Server! A server created for your entertainment and enjoyment.")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,50)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("To keep up to date with the latest Nyeblock news please join our steam group. Changes/Updates made to this server will be shown below.")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,65)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Becoming part of staff")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,85)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("If you would like to become part of staff on this server please open the application system by pressing F2. Depending on the position you are applying for")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,120)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("you will need to meet certain requirements.")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,135)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Your Nyeblock profile")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,155)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("To customize your Nyeblock profile open the server menu by pressing F1. This profile will represent you and will be shown in many menus within the")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,190)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("server. ")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,205)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Latest Change/Update")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,225)
	local viewUpdates = vgui.Create("DButton",pagepanel)
	viewUpdates:SetSize(75,25)
	viewUpdates:SetPos(lbl:GetWide()+lbl.x+10,227)
	viewUpdates:SetText("View all")
	viewUpdates:SetFont("roboto_15")
	viewUpdates:SetColor(Color(52,73,94))
	function viewUpdates:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function viewUpdates:DoClick()
		viewUpdates:SetEnabled(false)

		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,380)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
			viewUpdates:SetEnabled(true)
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("View Changes/Updates")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Please click the update you would like to view")
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,40)
		lbl:CenterHorizontal()
		local layoutScroll = vgui.Create("DScrollPanel",box)
		layoutScroll:SetSize(box:GetWide()-30,box:GetTall()-70)
		layoutScroll:SetPos(10,60)
		local layout = vgui.Create("DIconLayout",layoutScroll)
		layout:SetWide(layoutScroll:GetWide()-40)
		layout:SetPos(20,0)
		layout:SetSpaceY(10)
		local lbl = vgui.Create("DLabel",pagepanel)
		lbl:SetText("Loading...")
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		center(lbl,260)
		net.Start("nyeblock_getAllUpdates")
		net.SendToServer()
		net.Receive("nyeblock_returnAllUpdates",function()
			lbl:Remove()
			local updates = net.ReadTable()

			for k,v in pairs(updates) do
				updates[k].updates = util.JSONToTable(v.updates)

				local pnl = layout:Add("DPanel")
				pnl:SetSize(layout:GetWide(),40)
				function pnl:Paint(w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
					draw.RoundedBox(0,0,0,50,h,Color(149,165,166))
				end
				local updateVersion = vgui.Create("DLabel",pnl)
				updateVersion:SetSize(50,40)
				updateVersion:SetText("v"..(v.id*0.1)+1.0)
				updateVersion:SetFont("roboto_20")
				updateVersion:SetColor(Color(52,73,94))
				updateVersion:SetContentAlignment(5)
				local lbl = vgui.Create("DLabel",pnl)
				lbl:SetSize(pnl:GetWide()-70,pnl:GetTall())
				lbl:SetPos(60,0)
				lbl:SetText(#v.updates.." changes/updates |  Released "..os.date("%m/%d/%Y",v.created))
				lbl:SetFont("roboto_15")
				lbl:SetColor(Color(52,73,94))
				local buttonClick = vgui.Create("DButton",pnl)
				buttonClick:SetSize(pnl:GetWide(),pnl:GetTall())
				buttonClick:SetText("")
				function buttonClick:Paint() end
				function buttonClick:DoClick()
					box:SetVisible(false)

					local box2 = vgui.Create("DPanel",pagepanel)
					box2:SetSize(350,380)
					box2:Center()
					function box2:Paint(w,h)
						draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
						surface.SetDrawColor(149,165,166)
						surface.DrawOutlinedRect(0,0,w,h)
					end
					box2:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box2:GetTall()/2)
					box2:CenterHorizontal()
					local close = vgui.Create("DImageButton",box2)
					close:SetSize(15,15)
					close:SetImage("icon16/cross.png")
					close:SetPos(box2:GetWide()-close:GetWide()-10,10)
					function close:DoClick()
						box2:Remove()
						box:SetVisible(true)
					end
					local lbl = vgui.Create("DLabel",box2)
					lbl:SetText("v"..((v.id*0.1)+1.0).." Info")
					lbl:SetFont("roboto_25")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,10)
					lbl:CenterHorizontal()
					local lbl = vgui.Create("DLabel",box2)
					lbl:SetText("Released")
					lbl:SetFont("roboto_15")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,40)
					lbl:CenterHorizontal()
					local lbl = vgui.Create("DLabel",box2)
					lbl:SetText(os.date("%m/%d/%Y",v.created))
					lbl:SetFont("roboto_15")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,55)
					lbl:CenterHorizontal()
					local lbl = vgui.Create("DLabel",box2)
					lbl:SetText("Changes/Updates")
					lbl:SetFont("roboto_15")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,75)
					lbl:CenterHorizontal()
					local scroll = vgui.Create("DScrollPanel",box2)
					scroll:SetSize(box2:GetWide()-20,box2:GetTall()-105)
					scroll:SetPos(10,95)
					local itemLayout = vgui.Create("DIconLayout",scroll)
					itemLayout:SetWide(scroll:GetWide()-20)
					itemLayout:SetPos(10,0)
					for k2,v2 in pairs(v.updates) do
						local lbl = itemLayout:Add("DLabel")
						lbl:SetText("- "..v2)
						lbl:SetFont("roboto_15")
						lbl:SetColor(Color(52,73,94))
						lbl:SetWrap(true)
						lbl:SetAutoStretchVertical(true)
						lbl:SetWide(itemLayout:GetWide())
					end
				end
			end
		end)
	end
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Loading...")
	lbl:SetFont("roboto_15")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,260)
	net.Start("nyeblock_getLatestUpdate")
	net.SendToServer()
	net.Receive("nyeblock_returnLatestUpdate",function()
		lbl:Remove()
		local update = net.ReadTable()

		local pnl = vgui.Create("DPanel",pagepanel)
		pnl:SetSize(400,60)
		center(pnl,260)
		function pnl:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
			draw.RoundedBox(0,0,0,15,h,Color(149,165,166))
		end
		local name = vgui.Create("DLabel",pnl)
		name:SetText("Update (v"..((update.id*0.1)+1.0)..") - "..os.date("%m/%d/%Y",update.created))
		name:SetFont("oswald_28")
		name:SetColor(Color(52,73,94))
		name:SizeToContents()
		name:SetPos(20,0)
		local itemLayout = vgui.Create("DIconLayout",pnl)
		itemLayout:SetWide(pnl:GetWide()-45)
		itemLayout:SetPos(30,30)
		for k,v in pairs(util.JSONToTable(update.updates)) do
			local lbl = itemLayout:Add("DLabel")
			lbl:SetText("- "..v)
			lbl:SetFont("roboto_15")
			lbl:SetColor(Color(52,73,94))
			lbl:SetWrap(true)
			lbl:SetAutoStretchVertical(true)
			lbl:SetWide(itemLayout:GetWide())
		end
		timer.Simple(.1,function()
			if IsValid(pnl) then
				pnl:SizeToChildren(false,true)
				pnl:SetTall(pnl:GetTall()+10)
			end
		end)
	end)
end
local function rules()
	pagepanel:AlphaTo(255,.5,0)

	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Rules")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,15)
	local ruleLayout = vgui.Create("DIconLayout",pagepanel)
	ruleLayout:SetWide(pagepanel:GetWide()-20)
	ruleLayout:SetPos(10,50)
	ruleLayout:SetSpaceY(5)
	for k,v in pairs(NYEBLOCK.RULES) do
		local pnl = ruleLayout:Add("DPanel")
		pnl:SetSize(ruleLayout:GetWide(),70)
		function pnl:Paint() end
		local lbl = vgui.Create("DLabel",pnl)
		lbl:SetText(k..".) "..v.rule)
		lbl:SetFont("roboto_20")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(5,5)
		local lbl = vgui.Create("DLabel",pnl)
		lbl:SetText("Ex.) "..v.example)
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(15,30)
		local lbl = vgui.Create("DLabel",pnl)
		lbl:SetText("Breaking this rule will result in a "..v.discipline)
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(15,50)
	end
end
local function commands()
	pagepanel:AlphaTo(255,.5,0)
	local ypos = 50

	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Commands")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,15)
	local commandLayout = vgui.Create("DIconLayout",pagepanel)
	commandLayout:SetWide(pagepanel:GetWide()-20)
	commandLayout:SetPos(10,50)
	commandLayout:SetSpaceY(5)
	for k,v in pairs(NYEBLOCK.COMMANDS) do
		local lbl = vgui.Create("DLabel",pagepanel)
		lbl:SetText(v.text)
		lbl:SetFont("roboto_20")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(15,ypos)
		ypos = ypos + 25
		for k2,v2 in pairs(v.commands) do
			local lbl = vgui.Create("DLabel",pagepanel)
			lbl:SetText(v2)
			lbl:SetFont("roboto_15")
			lbl:SetColor(Color(52,73,94))
			lbl:SizeToContents()
			lbl:SetPos(25,ypos)
			ypos = ypos + 20
		end
	end
end

net.Receive("nyeblock_motd",function()
	local function motdMenu()
		panel = vgui.Create("DFrame")
		panel:SetSize(900,600)
		panel:Center()
		panel:SetTitle("")
		panel:SetDraggable(false)
		panel:ShowCloseButton(false)
		panel:MakePopup()
		function panel:Paint(w,h)
			draw.RoundedBox(0,0,40,w,h-40,Color(189,195,199))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,40,w,h-40)
		end
		local close = vgui.Create("DButton",panel)
		close:SetSize(100,30)
		close:SetText("CLOSE")
		close:SetColor(Color(52,73,94))
		close:SetFont("oswald_20")
		close:SetPos(panel:GetWide()-close:GetWide(),0)
		function close:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		function close:DoClick()
			panel:Close()
			net.Start("nyeblock_checkPoints")
			net.SendToServer()
		end
		local header = vgui.Create("DPanel",panel)
		header:SetSize(panel:GetWide(),65)
		header:SetPos(0,40)
		function header:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		local logo = vgui.Create("DImage",header)
		logo:SetImage("materials/nb/logo.png")
		logo:SetSize(100,100)
		logo:SetPos(0,-17)
		local lbl = vgui.Create("DLabel",header)
		lbl:SetText("MOTD")
		lbl:SetFont("oswald_30")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(95,0)
		lbl:CenterVertical()
		headerButtons[1] = vgui.Create("DButton",header)
		headerButtons[1]:SetSize(160,header:GetTall())
		headerButtons[1]:SetPos(160,0)
		headerButtons[1]:SetText("Home")
		headerButtons[1]:SetFont("buttonFont")
		headerButtons[1]:SetColor(Color(52,73,94))
		headerButtons[1].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		headerButtons[1].DoClick = function()
			pagepanel:Clear()
			pagepanel:SetAlpha(0)
			motd()
			menuselected = 1
			for k,v in pairs(headerButtons) do
				headerButtons[k].Paint = function(_,w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
				end
			end
			headerButtons[menuselected].Paint = function(_,w,h)
				draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
			end
		end
		headerButtons[2] = vgui.Create("DButton",header)
		headerButtons[2]:SetSize(160,header:GetTall())
		headerButtons[2]:SetPos(320,0)
		headerButtons[2]:SetText("Rules")
		headerButtons[2]:SetFont("buttonFont")
		headerButtons[2]:SetColor(Color(52,73,94))
		headerButtons[2].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		headerButtons[2].DoClick = function()
			pagepanel:Clear()
			pagepanel:SetAlpha(0)
			rules()
			menuselected = 2
			for k,v in pairs(headerButtons) do
				headerButtons[k].Paint = function(_,w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
				end
			end
			headerButtons[menuselected].Paint = function(_,w,h)
				draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
			end
		end
		headerButtons[3] = vgui.Create("DButton",header)
		headerButtons[3]:SetSize(160,header:GetTall())
		headerButtons[3]:SetPos(480,0)
		headerButtons[3]:SetText("Commands")
		headerButtons[3]:SetFont("buttonFont")
		headerButtons[3]:SetColor(Color(52,73,94))
		headerButtons[3].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		headerButtons[3].DoClick = function()
			pagepanel:Clear()
			pagepanel:SetAlpha(0)
			commands()
			menuselected = 3
			for k,v in pairs(headerButtons) do
				headerButtons[k].Paint = function(_,w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
				end
			end
			headerButtons[menuselected].Paint = function(_,w,h)
				draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
			end
		end
		headerButtons[4] = vgui.Create("DButton",header)
		headerButtons[4]:SetSize(160,header:GetTall())
		headerButtons[4]:SetPos(640,0)
		headerButtons[4]:SetText("Donate")
		headerButtons[4]:SetFont("buttonFont")
		headerButtons[4]:SetColor(Color(52,73,94))
		headerButtons[4].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		headerButtons[4].DoClick = function()
			gui.OpenURL("http://donate.nyeblock.com/deathrun/index.php?steamid="..LocalPlayer():SteamID())
		end

		pagepanel = vgui.Create("DScrollPanel",panel)
		pagepanel:SetSize(panel:GetWide()-40,425)
		pagepanel:SetPos(20,125)
		function pagepanel:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		local closeButton = vgui.Create("DButton",panel)
		closeButton:SetSize(panel:GetWide()-40,30)
		closeButton:SetPos(20,pagepanel:GetTall()+pagepanel.y)
		closeButton:SetText("Close this menu")
		closeButton:SetFont("roboto_20")
		closeButton:SetColor(Color(255,255,255))
		function closeButton:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(211,47,47))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		function closeButton:DoClick()
			panel:Close()
			net.Start("nyeblock_checkPoints")
			net.SendToServer()
		end

		motd()
	end
	local function season()
		local seasonData = nyeblock_getSeasonMenuInfo(nyeblock_getCurrentSeason())

		local background = vgui.Create("DHTML")
		background:SetHTML("<img width='"..ScrW().."' height='"..(ScrH()-35).."' style='overflow:hidden!important;' src='"..seasonData.backgroundImg.."'>")
		background:SetSize(ScrW(),ScrH())
		background:Center()
		local panel = vgui.Create("DPanel")
		panel:SetSize(600,400)
		panel:Center()
		panel:MakePopup()
		function panel:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h-50,Color(189,195,199))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,00,w,h-50)
		end
		local close = vgui.Create("DButton",panel)
		close:SetSize(185,30)
		close:SetPos(0,panel:GetTall()-40)
		close:CenterHorizontal()
		close:SetText("")
		function close:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		function close:DoClick()
			panel:Remove()
			background:Remove()
			net.Start("nyeblock_seasonReward")
			net.SendToServer()
			net.Start("nyeblock_checkPoints")
			net.SendToServer()
			motdMenu()
		end
		local closet = vgui.Create("DLabel",close)
		if seasonData.pointsInfo.givePoints then
			closet:SetText("CLOSE AND CLAIM POINTS")
		else
			closet:SetText("CLOSE")
		end
		closet:SetFont("nameFont5")
		closet:SetColor(Color(52,73,94))
		closet:SizeToContents()
		closet:Center()
		local pagepanel = vgui.Create("DPanel",panel)
		pagepanel:SetSize(panel:GetWide()-40,panel:GetTall()-90)
		pagepanel:SetPos(0,20)
		pagepanel:CenterHorizontal()
		function pagepanel:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		local lbl = vgui.Create("DLabel",pagepanel)
		lbl:SetText("Nyeblock "..seasonData.title.." Update")
		lbl:SetFont("menuFont")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local img = vgui.Create("DHTML",pagepanel)
		img:SetHTML("<img width='190' height='"..(pagepanel:GetTall()-95).."' src='"..seasonData.menuImg.."'>")
		img:SetSize(225,pagepanel:GetTall()-60)
		img:SetPos(10,55)
		local desc = vgui.Create("RichText",pagepanel)
		desc:SetSize(300,240)
		desc:SetPos(240,50)
		desc:InsertColorChange(52,73,94,255)
		for k,v in pairs(seasonData.updateFeatures) do
			desc:AppendText("- "..v.."\n")
		end
		function desc:PerformLayout()
			desc:SetFontInternal("playerCount")
		end
	end

	if net.ReadBool() then
		season()
	else
		motdMenu()
	end
end)