CreateClientConVar("deathrun_autojump",1,true,false)
CreateClientConVar("deathrun_autoredie",0,true,false)
CreateClientConVar("nyeblock_unmuteRTD",1,true,false)

surface.CreateFont("oswald_20",{font="Oswald",extended=false,size=20,weight=500})
surface.CreateFont("oswald_24",{font="Oswald",extended=false,size=24,weight=500})
surface.CreateFont("oswald_28",{font="Oswald",extended=false,size=28,weight=500})
surface.CreateFont("oswald_30",{font="Oswald",extended=false,size=30,weight=5000})
surface.CreateFont("roboto_30",{font="Roboto Black",extended=false,size=30,weight=500})
surface.CreateFont("roboto_25",{font="Roboto Black",extended=false,size=25,weight=500})
surface.CreateFont("roboto_20",{font="Roboto Black",extended=false,size=20,weight=500})
surface.CreateFont("roboto_15",{font="Roboto Black",extended=false,size=15,weight=500})
surface.CreateFont("regular_20",{font="",extended=false,size=20,weight=500})

local panel
local pagepanel
local function center(i,y)
	i:SetPos(pagepanel:GetWide()/2-i:GetWide()/2,y)
end

local function settings()
	pagepanel:AlphaTo(255,.5,0)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Settings")
	lbl:SetFont("oswald_28")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,15)
	local settingsLayout = vgui.Create("DIconLayout",pagepanel)
	settingsLayout:SetWide(pagepanel:GetWide()-40)
	settingsLayout:SetPos(20,50)
	settingsLayout:SetSpaceX(10)
	settingsLayout:SetSpaceY(10)
	local mutePlayers = settingsLayout:Add("DButton")
	mutePlayers:SetSize(197,50)
	mutePlayers:SetText("Mute players")
	mutePlayers:SetColor(Color(52,73,94))
	mutePlayers:SetFont("roboto_20")
	function mutePlayers:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function mutePlayers:DoClick()
		local checkboxes = {}

		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Mute players")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Please check the players you would like to mute")
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,40)
		lbl:CenterHorizontal()
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("then click the 'Mute Selected Players' button.")
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,55)
		lbl:CenterHorizontal()
		local playersLayoutScroll = vgui.Create("DScrollPanel",box)
		playersLayoutScroll:SetSize(box:GetWide()-20,box:GetTall()-140)
		playersLayoutScroll:SetPos(10,80)
		local playersLayout = vgui.Create("DIconLayout",playersLayoutScroll)
		playersLayout:SetWide(playersLayoutScroll:GetWide()-30)
		playersLayout:SetPos(10,0)
		playersLayout:SetSpaceY(10)
		for k,v in pairs(player.GetAll()) do
			local pnl = playersLayout:Add("DPanel")
			pnl:SetSize(playersLayout:GetWide(),50)
			function pnl:Paint(w,h)
				draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
				draw.RoundedBox(0,0,0,25,h,Color(149,165,166))
			end
			local avatarPanel = vgui.Create("DPanel",pnl)
			avatarPanel:SetSize(37,37)
			avatarPanel:SetPos(35,0)
			avatarPanel:CenterVertical()
			function avatarPanel:Paint(w,h)
				draw.RoundedBox(0,0,0,w,h,Color(149,165,166))
			end
			local avatar = vgui.Create("AvatarImage",avatarPanel)
			avatar:SetSize(35,35)
			avatar:SetPos(1,1)
			avatar:SetPlayer(v,64)
			local nick = vgui.Create("DLabel",pnl)
			nick:SetSize(pnl:GetWide()-90,30)
			nick:SetPos(80,0)
			nick:SetText(v:Nick())
			nick:SetFont("roboto_20")
			nick:SetColor(Color(52,73,94))
			nick:CenterVertical()
			checkboxes[k] = vgui.Create("DCheckBox",pnl)
			checkboxes[k]:SetPos(5,0)
			checkboxes[k].ply = v
			checkboxes[k]:CenterVertical()
			if v == LocalPlayer() or v:IsBot() or NYEBLOCK.FUNCTIONS.isStaff(v:GetUserGroup()) then
				checkboxes[k]:SetDisabled(true)
			end
			if v:IsMuted() then
				checkboxes[k]:SetChecked(true)
			end
		end
		local mute = vgui.Create("DButton",box)
		mute:SetSize(150,35)
		mute:SetText("Mute Selected Players")
		mute:SetFont("roboto_15")
		mute:SetColor(Color(52,73,94))
		mute:SetPos(0,box:GetTall()-mute:GetTall()-10)
		mute:CenterHorizontal()
		function mute:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		function mute:DoClick()
			for k2,v2 in pairs(checkboxes) do
				if v2.ply:IsMuted() then
					if v2:GetChecked() != true then
						v2.ply:SetMuted(false)
					end
				else
					if v2:GetChecked() then
						v2.ply:SetMuted(true)
					end
				end
			end
			NYEBLOCK.FUNCTIONS.createPopup("Successfully updated muted players!",1)
			box:Remove()
		end
	end
	local manageSounds = settingsLayout:Add("DButton")
	manageSounds:SetSize(197,50)
	manageSounds:SetText("Manage sounds")
	manageSounds:SetColor(Color(52,73,94))
	manageSounds:SetFont("roboto_20")
	function manageSounds:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function manageSounds:DoClick()
		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Manage sounds")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Here you can enable/disable sounds played on the server.")
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,40)
		lbl:CenterHorizontal()
		local layoutScroll = vgui.Create("DScrollPanel",box)
		layoutScroll:SetSize(box:GetWide()-20,box:GetTall()-70)
		layoutScroll:SetPos(10,60)
		local soundsLayout = vgui.Create("DIconLayout",layoutScroll)
		soundsLayout:SetWide(layoutScroll:GetWide()-120)
		soundsLayout:SetPos(60,0)
		soundsLayout:SetSpaceY(10)
		local rtdSounds = soundsLayout:Add("DButton")
		rtdSounds:SetSize(soundsLayout:GetWide(),50)
		rtdSounds:SetText("")
		function rtdSounds:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		local rtdSoundsInfo = vgui.Create("DImageButton",rtdSounds)
		rtdSoundsInfo:SetImage("icon16/information.png")
		rtdSoundsInfo:SetSize(15,15)
		rtdSoundsInfo:SetTooltip("This option includes every sound played within the RTD")
		rtdSoundsInfo:SetPos(rtdSounds:GetWide()-rtdSoundsInfo:GetWide()-5,5)
		local lbl = vgui.Create("DLabel",rtdSounds)
		lbl:SetText("RTD Sounds")
		lbl:SetColor(Color(52,73,94))
		lbl:SetFont("roboto_20")
		lbl:SizeToContents()
		lbl:SetPos(0,5)
		lbl:CenterHorizontal()
		local rtdSoundsStatus = vgui.Create("DLabel",rtdSounds)
		rtdSoundsStatus:SetText(GetConVar("nyeblock_unmuteRTD"):GetBool() and "Enabled" or "Disabled")
		rtdSoundsStatus:SetFont("roboto_15")
		rtdSoundsStatus:SetPos(0,27)
		rtdSoundsStatus:SetColor(GetConVar("nyeblock_unmuteRTD"):GetBool() and Color(0,255,0) or Color(255,0,0))
		rtdSoundsStatus:SizeToContents()
		rtdSoundsStatus:CenterHorizontal()
		function rtdSounds:DoClick()
			if GetConVar("nyeblock_unmuteRTD"):GetBool() then
				GetConVar("nyeblock_unmuteRTD"):SetBool(false)
			else
				GetConVar("nyeblock_unmuteRTD"):SetBool(true)
			end
			rtdSoundsStatus:SetText(GetConVar("nyeblock_unmuteRTD"):GetBool() and "Enabled" or "Disabled")
			rtdSoundsStatus:SetColor(GetConVar("nyeblock_unmuteRTD"):GetBool() and Color(0,255,0) or Color(255,0,0))
			rtdSoundsStatus:SizeToContents()
			rtdSoundsStatus:CenterHorizontal()
		end

		local jukeboxSounds = soundsLayout:Add("DButton")
		jukeboxSounds:SetSize(soundsLayout:GetWide(),50)
		jukeboxSounds:SetText("")
		function jukeboxSounds:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		local jukeboxSoundsInfo = vgui.Create("DImageButton",jukeboxSounds)
		jukeboxSoundsInfo:SetImage("icon16/information.png")
		jukeboxSoundsInfo:SetSize(15,15)
		jukeboxSoundsInfo:SetTooltip("This option includes every sound played within the Jukebox")
		jukeboxSoundsInfo:SetPos(jukeboxSounds:GetWide()-jukeboxSoundsInfo:GetWide()-5,5)
		local lbl = vgui.Create("DLabel",jukeboxSounds)
		lbl:SetText("Jukebox Music")
		lbl:SetColor(Color(52,73,94))
		lbl:SetFont("roboto_20")
		lbl:SizeToContents()
		lbl:SetPos(0,5)
		lbl:CenterHorizontal()
		local jukeboxSoundsStatus = vgui.Create("DLabel",jukeboxSounds)
		jukeboxSoundsStatus:SetText(JukeBox:GetCookie("JukeBox_Enabled") and "Enabled" or "Disabled")
		jukeboxSoundsStatus:SetFont("roboto_15")
		jukeboxSoundsStatus:SetPos(0,27)
		jukeboxSoundsStatus:SetColor(JukeBox:GetCookie("JukeBox_Enabled") and Color(0,255,0) or Color(255,0,0))
		jukeboxSoundsStatus:SizeToContents()
		jukeboxSoundsStatus:CenterHorizontal()
		function jukeboxSounds:DoClick()
			if JukeBox:GetCookie("JukeBox_Enabled") then
				JukeBox:SetCookie("JukeBox_Enabled",false)
				JukeBox:StopVideo()
				JukeBox:IsTunedIn( false )
			else
				JukeBox:SetCookie("JukeBox_Enabled",true)
				JukeBox:PlayReEnabled()
				JukeBox:IsTunedIn( true )
			end
			jukeboxSoundsStatus:SetText(JukeBox:GetCookie("JukeBox_Enabled") and "Enabled" or "Disabled")
			jukeboxSoundsStatus:SetColor(JukeBox:GetCookie("JukeBox_Enabled") and Color(0,255,0) or Color(255,0,0))
			jukeboxSoundsStatus:SizeToContents()
			jukeboxSoundsStatus:CenterHorizontal()
		end
	end
	local autoJump = settingsLayout:Add("DButton")
	autoJump:SetSize(197,50)
	autoJump:SetText("")
	function autoJump:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local autoJumpInfo = vgui.Create("DImageButton",autoJump)
	autoJumpInfo:SetImage("icon16/information.png")
	autoJumpInfo:SetSize(15,15)
	autoJumpInfo:SetPos(autoJump:GetWide()-autoJumpInfo:GetWide()-5,5)
	function autoJumpInfo:DoClick()
		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Auto Jump")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local text = vgui.Create("DLabel",box)
		text:SetSize(box:GetWide()-20,box:GetTall()-50)
		text:SetPos(10,40)
		text:SetText("Auto jump is exactly how it sounds. If enabled and you are holding your jump button you will continue jumping. If disabled and you are holding the jump button you will only jump once.")
		text:SetWrap(true)
		text:SetFont("roboto_15")
		text:SetContentAlignment(7)
		text:SetColor(Color(52,73,94))
	end
	local lbl = vgui.Create("DLabel",autoJump)
	lbl:SetText("Auto Jump")
	lbl:SetColor(Color(52,73,94))
	lbl:SetFont("roboto_20")
	lbl:SizeToContents()
	lbl:SetPos(0,5)
	lbl:CenterHorizontal()
	local autoJumpStatus = vgui.Create("DLabel",autoJump)
	autoJumpStatus:SetText(GetConVar("deathrun_autojump"):GetBool() and "Enabled" or "Disabled")
	autoJumpStatus:SetFont("roboto_15")
	autoJumpStatus:SetPos(0,27)
	autoJumpStatus:SetColor(GetConVar("deathrun_autojump"):GetBool() and Color(0,255,0) or Color(255,0,0))
	autoJumpStatus:SizeToContents()
	autoJumpStatus:CenterHorizontal()
	function autoJump:DoClick()
		if GetConVar("deathrun_autojump"):GetBool() then
			GetConVar("deathrun_autojump"):SetBool(false)
		else
			GetConVar("deathrun_autojump"):SetBool(true)
		end
		autoJumpStatus:SetText(GetConVar("deathrun_autojump"):GetBool() and "Enabled" or "Disabled")
		autoJumpStatus:SetColor(GetConVar("deathrun_autojump"):GetBool() and Color(0,255,0) or Color(255,0,0))
		autoJumpStatus:SizeToContents()
		autoJumpStatus:CenterHorizontal()
	end
	local autoRedie = settingsLayout:Add("DButton")
	autoRedie:SetSize(197,50)
	autoRedie:SetText("")
	function autoRedie:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local autoRedieInfo = vgui.Create("DImageButton",autoRedie)
	autoRedieInfo:SetImage("icon16/information.png")
	autoRedieInfo:SetSize(15,15)
	autoRedieInfo:SetPos(autoRedie:GetWide()-autoRedieInfo:GetWide()-5,5)
	function autoRedieInfo:DoClick()
		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Auto Redie")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local text = vgui.Create("DLabel",box)
		text:SetSize(box:GetWide()-20,box:GetTall()-50)
		text:SetPos(10,40)
		text:SetText("If enabled you will automatically enter redie mode when you die. If disabled you will die and enter spectating mode like normal.")
		text:SetWrap(true)
		text:SetFont("roboto_15")
		text:SetContentAlignment(7)
		text:SetColor(Color(52,73,94))
	end
	local lbl = vgui.Create("DLabel",autoRedie)
	lbl:SetText("Auto Redie")
	lbl:SetColor(Color(52,73,94))
	lbl:SetFont("roboto_20")
	lbl:SizeToContents()
	lbl:SetPos(0,5)
	lbl:CenterHorizontal()
	local autoRedieStatus = vgui.Create("DLabel",autoRedie)
	autoRedieStatus:SetText(GetConVar("deathrun_autoredie"):GetBool() and "Enabled" or "Disabled")
	autoRedieStatus:SetFont("roboto_15")
	autoRedieStatus:SetPos(0,27)
	autoRedieStatus:SetColor(GetConVar("deathrun_autoredie"):GetBool() and Color(0,255,0) or Color(255,0,0))
	autoRedieStatus:SizeToContents()
	autoRedieStatus:CenterHorizontal()
	function autoRedie:DoClick()
		if GetConVar("deathrun_autoredie"):GetBool() then
			GetConVar("deathrun_autoredie"):SetBool(false)
		else
			GetConVar("deathrun_autoredie"):SetBool(true)
		end
		autoRedieStatus:SetText(GetConVar("deathrun_autoredie"):GetBool() and "Enabled" or "Disabled")
		autoRedieStatus:SetColor(GetConVar("deathrun_autoredie"):GetBool() and Color(0,255,0) or Color(255,0,0))
		autoRedieStatus:SizeToContents()
		autoRedieStatus:CenterHorizontal()
	end
	local toggleTrails = settingsLayout:Add("DButton")
	toggleTrails:SetSize(197,50)
	toggleTrails:SetText("")
	function toggleTrails:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local toggleTrailsInfo = vgui.Create("DImageButton",toggleTrails)
	toggleTrailsInfo:SetImage("icon16/information.png")
	toggleTrailsInfo:SetSize(15,15)
	toggleTrailsInfo:SetPos(toggleTrails:GetWide()-toggleTrailsInfo:GetWide()-5,5)
	function toggleTrailsInfo:DoClick()
		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Trails")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local text = vgui.Create("DLabel",box)
		text:SetSize(box:GetWide()-20,box:GetTall()-50)
		text:SetPos(10,40)
		text:SetText("If enabled trails will be shown like normal. If disabled trails will not be rendered. This can help reduce lag and increase fps.")
		text:SetWrap(true)
		text:SetFont("roboto_15")
		text:SetContentAlignment(7)
		text:SetColor(Color(52,73,94))
	end
	local lbl = vgui.Create("DLabel",toggleTrails)
	lbl:SetText("Trails")
	lbl:SetColor(Color(52,73,94))
	lbl:SetFont("roboto_20")
	lbl:SizeToContents()
	lbl:SetPos(0,5)
	lbl:CenterHorizontal()
	local trailsStatus = vgui.Create("DLabel",toggleTrails)
	trailsStatus:SetText(!GetConVar("nl_hide_trails"):GetBool() and "Enabled" or "Disabled")
	trailsStatus:SetFont("roboto_15")
	trailsStatus:SetPos(0,27)
	trailsStatus:SetColor(!GetConVar("nl_hide_trails"):GetBool() and Color(0,255,0) or Color(255,0,0))
	trailsStatus:SizeToContents()
	trailsStatus:CenterHorizontal()
	function toggleTrails:DoClick()
		if GetConVar("nl_hide_trails"):GetBool() then
			GetConVar("nl_hide_trails"):SetBool(false)
		else
			GetConVar("nl_hide_trails"):SetBool(true)
		end
		trailsStatus:SetText(!GetConVar("nl_hide_trails"):GetBool() and "Enabled" or "Disabled")
		trailsStatus:SetColor(!GetConVar("nl_hide_trails"):GetBool() and Color(0,255,0) or Color(255,0,0))
		trailsStatus:SizeToContents()
		trailsStatus:CenterHorizontal()
	end
	local toggleVapeSmoke = settingsLayout:Add("DButton")
	toggleVapeSmoke:SetSize(197,50)
	toggleVapeSmoke:SetText("")
	function toggleVapeSmoke:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local toggleVapeInfo = vgui.Create("DImageButton",toggleVapeSmoke)
	toggleVapeInfo:SetImage("icon16/information.png")
	toggleVapeInfo:SetSize(15,15)
	toggleVapeInfo:SetPos(toggleVapeSmoke:GetWide()-toggleVapeInfo:GetWide()-5,5)
	function toggleVapeInfo:DoClick()
		local box = vgui.Create("DPanel",pagepanel)
		box:SetSize(400,280)
		box:Center()
		function box:Paint(w,h)
			draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
		box:SetPos(0,pagepanel:GetVBar():GetScroll()+pagepanel:GetTall()/2-box:GetTall()/2)
		box:CenterHorizontal()
		local close = vgui.Create("DImageButton",box)
		close:SetSize(15,15)
		close:SetImage("icon16/cross.png")
		close:SetPos(box:GetWide()-close:GetWide()-10,10)
		function close:DoClick()
			box:Remove()
		end
		local lbl = vgui.Create("DLabel",box)
		lbl:SetText("Vape Smoke")
		lbl:SetFont("roboto_25")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		lbl:SetPos(0,10)
		lbl:CenterHorizontal()
		local text = vgui.Create("DLabel",box)
		text:SetSize(box:GetWide()-20,box:GetTall()-50)
		text:SetPos(10,40)
		text:SetText("If enabled vape smoke will be shown like normal. If disabled vape smoke will not be rendered. This can help reduce lag and increase fps.")
		text:SetWrap(true)
		text:SetFont("roboto_15")
		text:SetContentAlignment(7)
		text:SetColor(Color(52,73,94))
	end
	local lbl = vgui.Create("DLabel",toggleVapeSmoke)
	lbl:SetText("Vape Smoke")
	lbl:SetColor(Color(52,73,94))
	lbl:SetFont("roboto_20")
	lbl:SizeToContents()
	lbl:SetPos(0,5)
	lbl:CenterHorizontal()
	local vapeSmokeStatus = vgui.Create("DLabel",toggleVapeSmoke)
	vapeSmokeStatus:SetText(!GetConVar("nl_hide_vape"):GetBool() and "Enabled" or "Disabled")
	vapeSmokeStatus:SetFont("roboto_15")
	vapeSmokeStatus:SetPos(0,27)
	vapeSmokeStatus:SetColor(!GetConVar("nl_hide_vape"):GetBool() and Color(0,255,0) or Color(255,0,0))
	vapeSmokeStatus:SizeToContents()
	vapeSmokeStatus:CenterHorizontal()
	function toggleVapeSmoke:DoClick()
		if GetConVar("nl_hide_vape"):GetBool() then
			GetConVar("nl_hide_vape"):SetBool(false)
		else
			GetConVar("nl_hide_vape"):SetBool(true)
		end
		vapeSmokeStatus:SetText(!GetConVar("nl_hide_vape"):GetBool() and "Enabled" or "Disabled")
		vapeSmokeStatus:SetColor(!GetConVar("nl_hide_vape"):GetBool() and Color(0,255,0) or Color(255,0,0))
		vapeSmokeStatus:SizeToContents()
		vapeSmokeStatus:CenterHorizontal()
	end
end
local function howToPlay()
	pagepanel:AlphaTo(255,.5,0)
	local lbl = vgui.Create("DLabel",pagepanel)
	lbl:SetText("Welcome to NyeBlock's Deathrun server!")
	lbl:SetFont("roboto_30")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	center(lbl,15)
	local ypos = 55
	for k,v in pairs(string.Explode( "\n", GAMEMODE.MenuText )) do
		local lbl = vgui.Create("DLabel",pagepanel)
		lbl:SetText(v)
		lbl:SetFont("roboto_15")
		lbl:SetColor(Color(52,73,94))
		lbl:SizeToContents()
		center(lbl,ypos)
		ypos = ypos + 20
	end
end

net.Receive("nyeblock_f1Menu",function()
	local menuselected = 1
	local headerButtons = {}
	local headerButtonArrows = {}
	local buttonSubmenus = {}
	local function closeDropdowns()
		for k,v in pairs(buttonSubmenus) do
			v:SetVisible(false)
			headerButtonArrows[k]:SetText("⯅")
		end
	end
	if IsValid(panel) then panel:Close() end

	panel = vgui.Create("DFrame")
	panel:SetSize(900,600)
	panel:Center()
	panel:SetTitle("")
	panel:SetDraggable(false)
	panel:ShowCloseButton(false)
	panel:MakePopup()
	function panel:Paint(w,h)
		draw.RoundedBox(0,0,40,w,h-40,Color(189,195,199))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,40,w,h-40)
	end
	local close = vgui.Create("DButton",panel)
	close:SetSize(100,30)
	close:SetText("CLOSE")
	close:SetColor(Color(52,73,94))
	close:SetFont("oswald_20")
	close:SetPos(panel:GetWide()-close:GetWide(),0)
	function close:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function close:DoClick()
		panel:Close()
	end
	local header = vgui.Create("DPanel",panel)
	header:SetSize(panel:GetWide(),65)
	header:SetPos(0,40)
	function header:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local logo = vgui.Create("DImage",header)
	logo:SetImage("materials/nb/logo.png")
	logo:SetSize(100,100)
	logo:SetPos(0,-17)
	local lbl = vgui.Create("DLabel",header)
	lbl:SetText("Deathrun Server Menu")
	lbl:SetFont("oswald_30")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	lbl:SetPos(95,0)
	lbl:CenterVertical()
	headerButtons[1] = vgui.Create("DButton",header)
	headerButtons[1]:SetSize(160,header:GetTall())
	headerButtons[1]:SetPos(280,0)
	headerButtons[1]:SetText("How to play")
	headerButtons[1]:SetFont("buttonFont")
	headerButtons[1]:SetColor(Color(52,73,94))
	headerButtons[1].Paint = function(_,w,h)
		draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	headerButtons[1].DoClick = function()
		pagepanel:Clear()
		pagepanel:SetAlpha(0)
		howToPlay()
		menuselected = 1
		for k,v in pairs(headerButtons) do
			headerButtons[k].Paint = function(_,w,h)
				draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
			end
		end
		headerButtons[menuselected].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
	end
	headerButtons[2] = vgui.Create("DButton",header)
	headerButtons[2]:SetSize(160,header:GetTall())
	headerButtons[2]:SetPos(440,0)
	headerButtons[2]:SetText("Settings")
	headerButtons[2]:SetFont("buttonFont")
	headerButtons[2]:SetColor(Color(52,73,94))
	headerButtons[2].Paint = function(_,w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	headerButtons[2].DoClick = function()
		pagepanel:Clear()
		pagepanel:SetAlpha(0)
		settings()
		menuselected = 2
		closeDropdowns()
		for k,v in pairs(headerButtons) do
			headerButtons[k].Paint = function(_,w,h)
				draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
				surface.SetDrawColor(149,165,166)
				surface.DrawOutlinedRect(0,0,w,h)
			end
		end
		headerButtons[menuselected].Paint = function(_,w,h)
			draw.RoundedBox(0,0,0,w,h,Color(189,195,199))
			surface.SetDrawColor(149,165,166)
			surface.DrawOutlinedRect(0,0,w,h)
		end
	end
	pagepanel = vgui.Create("DScrollPanel",panel)
	pagepanel:SetSize(panel:GetWide()-40,455)
	pagepanel:SetPos(20,125)
	function pagepanel:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	howToPlay()
end)