surface.CreateFont("dnameFont5",{font="Oswald",extended=false,size=20,weight=500})
surface.CreateFont("dnameFont4",{font="Oswald",extended=false,size=25,weight=500})
surface.CreateFont("dmenuFont",{font="Oswald",extended=false,size=30,weight=5000})
surface.CreateFont("dplayerCount",{font="Roboto Black",extended=false,size=15,weight=500})
surface.CreateFont("dplayerCount2",{font="Roboto Black",extended=false,size=13,weight=500})
surface.CreateFont("dnameFont2",{font="Roboto Black",extended=false,size=22,weight=500})
surface.CreateFont("dbuttonFont",{font="Roboto Black",extended=false,size=25,weight=500})
surface.CreateFont("dbuttonFont3",{font="Roboto Black",extended=false,size=15,weight=500})

net.Receive("nyeblock_donationPanel",function()
	local credits = tonumber(net.ReadString())
	local season = nyeblock_getCurrentSeason()
	local seasonData = nyeblock_getSeasonMenuInfo(season)

	local panel = vgui.Create("DPanel")
	panel:SetSize(700,500)
	panel:Center()
	panel:MakePopup()
	function panel:Paint(w,h)
		draw.RoundedBox(0,0,40,w,h-40,Color(189,195,199))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,40,w,h-40)
	end
	local close = vgui.Create("DButton",panel)
	close:SetSize(100,30)
	close:SetPos(panel:GetWide()-close:GetWide(),0)
	close:SetText("")
	function close:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function close:DoClick()
		panel:Remove()
	end
	local closet = vgui.Create("DLabel",close)
	closet:SetText("CLOSE")
	closet:SetFont("dnameFont5")
	closet:SetColor(Color(52,73,94))
	closet:SizeToContents()
	closet:Center()
	local header = vgui.Create("DPanel",panel)
	header:SetSize(panel:GetWide(),45)
	header:SetPos(0,40)
	function header:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local lbl = vgui.Create("DLabel",header)
	if season != nil then
		lbl:SetText("Donation Packages ("..seasonData.title.." Sale)")
	else
		lbl:SetText("Donation Packages")
	end
	lbl:SetFont("dmenuFont")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	lbl:Center()
	local img = vgui.Create("DImage",header)
	img:SetImage("icon16/money.png")
	img:SetSize(15,15)
	img:SetPos(520,0)
	img:CenterVertical()
	local creditss = vgui.Create("DLabel",header)
	creditss:SetText("You have "..credits.." credits")
	creditss:SetFont("dplayerCount")
	creditss:SetColor(Color(52,73,94))
	creditss:SizeToContents()
	creditss:SetPos(540,0)
	creditss:CenterVertical()
	local button = vgui.Create("DButton",header)
	button:SetSize(125,25)
	button:SetPos(25,0)
	button:CenterVertical()
	button:SetText("")
	function button:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	function button:DoClick()
		gui.OpenURL("http://donate.nyeblock.com/deathrun/index.php?steamid="..LocalPlayer():SteamID())
	end
	local img = vgui.Create("DImage",button)
	img:SetImage("icon16/world_add.png")
	img:SetSize(17,17)
	img:SetPos(5,0)
	img:CenterVertical()
	local lbl = vgui.Create("DLabel",button)
	lbl:SetText("Purchase credits")
	lbl:SetFont("dbuttonFont3")
	lbl:SetColor(Color(52,73,94))
	lbl:SizeToContents()
	lbl:SetPos(25,0)
	lbl:CenterVertical()
	local pagepanel = vgui.Create("DScrollPanel",panel)
	pagepanel:SetSize(panel:GetWide()-40,panel:GetTall()-125)
	pagepanel:SetPos(20,105)
	function pagepanel:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local listpnl = vgui.Create("DIconLayout",pagepanel)
	listpnl:SetWide(pagepanel:GetWide()-40)
	listpnl:SetPos(20,20)
	listpnl:SetSpaceX(10)
	listpnl:SetSpaceY(10)
	local function displayPackages()
		for k,v in pairs(NYEBLOCK.DONATION_PACKAGES) do
			local canView = true
			if v.restrictedGroups != nil and table.HasValue(v.restrictedGroups,LocalPlayer():GetUserGroup()) then 
				canView = false
			end
			if canView then
				local box = listpnl:Add("DPanel")
				box:SetSize(200,90)
				function box:Paint(w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
				end
				local name = vgui.Create("DLabel",box)
				name:SetText(string.upper(v.name))
				name:SetFont("dnameFont2")
				name:SetColor(Color(52,73,94))
				name:SizeToContents()
				name:SetPos(0,10)
				name:CenterHorizontal()
				local price = vgui.Create("DLabel",box)
				price:SetText(v.price.." credits")
				price:SetFont("dplayerCount")
				price:SetColor(Color(52,73,94))
				price:SizeToContents()
				price:SetPos(0,30)
				price:CenterHorizontal()
				local view = vgui.Create("DButton",box)
				view:SetSize(125,25)
				view:SetPos(0,50)
				view:CenterHorizontal()
				view:SetText("")
				function view:Paint(w,h)
					draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
					surface.SetDrawColor(149,165,166)
					surface.DrawOutlinedRect(0,0,w,h)
				end
				function view:DoClick()
					local box = vgui.Create("DPanel",pagepanel)
					box:SetSize(400,285)
					box:SetPos(0,50)
					box:CenterHorizontal()
					function box:Paint(w,h)
						draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
						surface.SetDrawColor(149,165,166)
						surface.DrawOutlinedRect(0,0,w,h)
					end
					local close = vgui.Create("DImageButton",box)
					close:SetSize(15,15)
					close:SetImage("icon16/cross.png")
					close:SetPos(box:GetWide()-close:GetWide()-10,10)
					function close:DoClick()
						box:Remove()
					end
					local lbl = vgui.Create("DLabel",box)
					lbl:SetText(v.name)
					lbl:SetFont("dbuttonFont")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,10)
					lbl:CenterHorizontal()
					local description = vgui.Create("RichText",box)
					description:SetSize(box:GetWide()-20,155)
					description:SetPos(10,50)
					description:InsertColorChange(52,73,94,255)
					description:AppendText(v.description)
					description:CenterHorizontal()
					local lbl = vgui.Create("DLabel",box)
					if season != nil then
						lbl:SetText("Price: "..v.price.." credits ("..(seasonData.packageSale*100).."% off)")
					else
						lbl:SetText("Price: "..v.price.." credits")
					end
					lbl:SetFont("dbuttonFont3")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:SetPos(0,225)
					lbl:CenterHorizontal()
					local purchase = vgui.Create("DButton",box)
					purchase:SetSize(100,30)
					purchase:SetPos(0,245)
					purchase:SetText("")
					purchase:CenterHorizontal()
					function purchase:Paint(w,h)
						draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
						surface.SetDrawColor(149,165,166)
						surface.DrawOutlinedRect(0,0,w,h)
					end
					function purchase:DoClick()
						if credits >= v.price then
							local tbl = {
								name = v.name,
								type = v.type,
								steamid64 = LocalPlayer():SteamID64(),
								price = v.price
							}
							if v.type == "rank" then
								tbl["ulxgroups"] = v.ulxgroups
								tbl["points"] = v.points
							elseif v.type == "points" then
								tbl["points"] = v.points
							else
								tbl["amount"] = v.amount
							end
							net.Start("nyeblock_purchaseDonationPackage")
								net.WriteTable(tbl)
							net.SendToServer()
							credits = credits - v.price
							creditss:SetText("You have "..credits.." credits")
							panel:Remove()
							ap_createPopup("Donation package successfully purchased!",1)
						else
							ap_createPopup("You do not have enough credits to purchase this package!",2)
						end
					end
					local lbl = vgui.Create("DLabel",purchase)
					lbl:SetText("Purchase")
					lbl:SetFont("dbuttonFont3")
					lbl:SetColor(Color(52,73,94))
					lbl:SizeToContents()
					lbl:Center()
				end
				local viewt = vgui.Create("DLabel",view)
				viewt:SetText("View Package")
				viewt:SetFont("dplayerCount2")
				viewt:SetColor(Color(52,73,94))
				viewt:SizeToContents()
				viewt:Center()
			end
		end
	end
	net.Start("nyeblock_checkForDonation")
	net.SendToServer()
	net.Receive("nyeblock_autoRefreshPoints",function()
		credits = credits + net.ReadString()
		creditss:SetText("You have "..credits.." credits")
		creditss:SizeToContents()
	end)
	displayPackages()
end)
net.Receive("nyeblock_donationNotification",function()
	local player = net.ReadTable()
	local box = vgui.Create("DPanel")
	box:SetSize(300,75)
	box:SetPos(ScrW()/2-box:GetWide()/2,-box:GetTall())
	box:MoveTo(ScrW()/2-box:GetWide()/2,5,.5,0,1)
	function box:Paint(w,h)
		draw.RoundedBox(0,0,0,w,h,Color(236,240,241))
		surface.SetDrawColor(149,165,166)
		surface.DrawOutlinedRect(0,0,w,h)
	end
	local lbl = vgui.Create("DLabel",box)
	lbl:SetText(player.name.." has donated")
	lbl:SetFont("dnameFont4")
	lbl:SizeToContents()
	lbl:SetPos(0,10)
	lbl:CenterHorizontal()
	function lbl:Paint()
		lbl:SetColor(Color(255*math.abs(math.sin(CurTime())),255*math.abs(math.sin(CurTime()+1.8)),255*math.abs(math.sin(CurTime()+2.6))))
	end
	local lbl = vgui.Create("DLabel",box)
	lbl:SetText("They received "..player.package)
	lbl:SetFont("dnameFont5")
	lbl:SizeToContents()
	lbl:SetPos(0,40)
	lbl:CenterHorizontal()
	function lbl:Paint()
		lbl:SetColor(Color(255*math.abs(math.sin(CurTime())),255*math.abs(math.sin(CurTime()+1.8)),255*math.abs(math.sin(CurTime()+2.6))))
	end
	timer.Simple(7,function()
		box:MoveTo(ScrW()/2-box:GetWide()/2,-box:GetTall(),.5,0,1)
		timer.Simple(2,function()
			box:Remove()
		end)
	end)
end)